routes/web.php
<?php


use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('home');
Route::get('/orcamentos', 'PagesController@orcamentos')->name('orcamento');
Route::get('/despesas', 'PagesController@despesas')->name('despesas');
Route::get('/receitas', 'PagesController@receitas')->name('receitas');
Route::get('/servidores', 'PagesController@servidores')->name('servidores');
Route::get('/licitacoes', 'PagesController@licitacoes')->name('licitacoes');

Route::get('/contratos', 'PagesController@contratos')->name('contratos');
Route::get('/atas-resgitro-pagemento', 'PagesController@atas')->name('atas');
Route::get('/dispensa-licitacao', 'PagesController@dispensa')->name('dispensa');
Route::get('/concorrencia', 'PagesController@concorrencia')->name('concorrencia');
Route::get('/carta-convite', 'PagesController@cartaConvite')->name('carta');
Route::get('/contrato-pessoa-fisica', 'PagesController@contratoPessoaFisica')->name('contrato.fisica');
Route::get('/contrato-pessoa-juridica', 'PagesController@contratoPessoaJuridica')->name('contrato.juridica');
Route::get('/inexigibilidade', 'PagesController@inexigibilidade')->name('inexigibilidade');
Route::get('/pregao-presencial', 'PagesController@pregaoPresencial')->name('pregao.presencial');
Route::get('/pregao-eletronico', 'PagesController@pregaoEletronico')->name('pregao.eletronico');
Route::get('/tomada-precos', 'PagesController@tomadaDePrecos')->name('tomada.precos');


Route::get('/diarias', 'PagesController@diarias')->name('diarias');
Route::get('/publicacoes-oficiais', 'PagesController@publicacoesOficiais')->name('publicacoes-oficiais');
Route::get('/legislacoes', 'PagesController@legislacoes')->name('legislacoes');
Route::get('/pedidos-esic', 'PagesController@esic');
Route::post('/salvar-pedido', 'PagesController@salvarPedido')->name('salvarPedido');
Route::get('/salvar-pedido/consultar', 'PagesController@consultarPedido')->name('consultarPedido');
Route::post('/responder-pedido', 'PagesController@responderPedido')->name('responderPedido');
Route::get('/covid19', 'PagesController@covid19')->name('covid19');
Route::get('/covid19-despesas', 'PagesController@covid19Desespesas')->name('covid19-despesas');
Route::get('/covid19-receitas', 'PagesController@covid19Receitas')->name('covid19-receitas');
Route::get('/covid19-licitacoes', 'PagesController@covid19Licitacoes')->name('covid19-licitacoes');
Route::get('/covid19-contratos', 'PagesController@covid19Contratos')->name('covid19-contratos');
Route::get('/estatisticas', 'PagesController@estatisticas')->name('estatisticas');
Route::get('/estrutura-organizacional', 'PagesController@estruturas')->name('estrutura-organizacional');
Route::get('/lrf', 'PagesController@lrf')->name('lrf');
Route::get('/verbas', 'PagesController@verbas')->name('verba');
Route::post('/search-options','SearchController@searchOptions')->name('search');
Route::fallback(function () {
    return redirect()->route('home');
});

// Demo routes
// Route::get('/dashboards', 'PagesController@dashboards');
// Route::get('/datatables', 'PagesController@datatables');
// Route::get('/ktdatatables', 'PagesController@ktDatatables');
// Route::get('/select2', 'PagesController@select2');
// Route::get('/jquerymask', 'PagesController@jQueryMask');
// Route::get('/icons/custom-icons', 'PagesController@customIcons');
// Route::get('/icons/flaticon', 'PagesController@flaticon');
// Route::get('/icons/fontawesome', 'PagesController@fontawesome');
// Route::get('/icons/lineawesome', 'PagesController@lineawesome');
// Route::get('/icons/socicons', 'PagesController@socicons');
// Route::get('/icons/svg', 'PagesController@svg');

// Quick search dummy route to display html elements in search dropdown (header search)
// Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

Route::prefix('adm')->group(function () {
    Auth::routes(['register' => false]);
    Route::middleware(['auth'])->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home_adm');
        Route::resource('users', UserController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('app-settings', AppSettingController::class);
        Route::resource('attachments', AttachmentController::class);
        Route::resource('type-documents', TypeDocumentController::class);
        Route::resource('documents', DocumentController::class);
        Route::resource('attachment-documents', AttachmentDocumentController::class);
        Route::resource('verbas', VerbaController::class);
        Route::resource('attachment-verbas', AttachmentVerbaController::class);
        Route::resource('empenhos', EmpenhoController::class);
        Route::resource('attachment-empenhos', AttachmentEmpenhoController::class);
        Route::resource('pagamentos', PagamentoController::class);
        Route::resource('liquidacoes', LiquidacaoController::class);
        Route::resource('receitas', ReceitaController::class);
        Route::resource('attachment-receitas', AttachmentReceitaController::class);
        Route::resource('cargos', CargoController::class);
        Route::resource('servidores', ServidorController::class);
        Route::get('servidores/{id}/restore', [App\Http\Controllers\ServidorController::class, 'restore'])->name('servidores.restore');
        Route::resource('attachment-servidores', AttachmentServidorController::class);
        Route::resource('contratos', ContratoController::class);
        Route::resource('attachment-contratos', AttachmentContratoController::class);
        Route::resource('diarias', DiariaController::class);
        Route::resource('attachment-diarias', AttachmentDiariaController::class);
        Route::resource('tipo-planejamento-orcamentarios', TipoPlanejamentoOrcamentarioController::class);
        Route::resource('arquivo-plan-orcamentarios', ArquivoPlanOrcamentarioController::class);
        Route::resource('covid-resumos', CovidResumoController::class);
        Route::resource('estruturas', EstruturaController::class);
        Route::resource('responsabilidades', ResponsabilidadeController::class);
        Route::resource('arquivo-responsabilidades', ArquivoResponsabilidadeController::class);

        Route::prefix('sicap')->group(function () {
            Route::resource('sicap-empenho', SicapEmpenhoController::class);
            Route::get('sicap-empenho/{id}/restore', [App\Http\Controllers\SicapEmpenhoController::class, 'restore'])->name('sicap-empenho.restore');

            Route::resource('sicap-servidores', SicapServidorController::class);
            Route::get('sicap-servidores/{id}/restore', [App\Http\Controllers\SicapServidorController::class, 'restore'])->name('sicap-servidor.restore');

            Route::resource('sicap-receitas', SicapReceitaController::class);
            Route::get('sicap-receitas/{id}/restore', [App\Http\Controllers\SicapReceitaController::class, 'restore'])->name('sicap-receitas.restore');
        });
        Route::prefix('siap')->group(function () {
            Route::resource('siap-empenho', SiapEmpenhoController::class);
            Route::get('siap-empenho/{id}/restore', [App\Http\Controllers\SiapEmpenhoController::class, 'restore'])->name('siap-empenho.restore');
        });
        Route::prefix('sagres')->group(function () {
            Route::resource('sagres-empenhos', SagresEmpenhoController::class);
            Route::get('sagres-empenho/{id}/restore', [App\Http\Controllers\SagresEmpenhoController::class, 'restore'])->name('sagres-empenho.restore');
        });

        Route::resource('pedidos', PedidoController::class);
        Route::resource('controle-menu',OptionController::class);
        Route::get('controle-submenu/{id}',[App\Http\Controllers\OptionController::class,'editSubmenu'])->name('submenu.edit');
        Route::put('controle-submenu/{id}',[App\Http\Controllers\OptionController::class,'updateSubmenu'])->name('submenu.update');
        Route::resource('respostas', RespostaController::class);
        Route::resource('tipo-pedidos', TipoPedidoController::class);
    });
});

app/Models/SagresEmpenho.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class SagresEmpenho extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable
     *
     * @var array
     */
     protected $table = 'sagres_empenhos';
     protected $fillable = [
        'ano',
        'cod_unid_orc',
        'funcao',
        'subfuncao',
        'programa',
        'acao',
        'id_acao',
        'cod_cat_econ',
        'cod_nat_desp',
        'modalidade_aplic',
        'cod_elem_desp_dot',
        'sub_elem_desp',
        'modalidade_licit',
        'num_empenho',
        'tipo_empenho',
        'data_emissao_empenho',
        'valor_empenhado',
        'historico',
        'cpf_cnpj_credor',
        'num_procedimento',
        'font_recurso',
        'cpf_ordenador',
        'cod_elem_desp'
     ];

    /**
     * Get the credor that owns the SagresEmpenho
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function credor(): BelongsTo
    {
        return $this->belongsTo(SagresCredor::class, 'cpf_cnpj_credor', 'cpf_cnpj');
    }

    /**
     * Get the funcao that owns the SagresFuncao
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function funcao(): BelongsTo
    {
        return $this->belongsTo(SagresFuncao::class, 'funcao', 'codigo');
    }

    /**
     * Get the subFuncao that owns the SagresSubFuncao
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function subfuncao(): BelongsTo
    {
        return $this->belongsTo(SagresSubFuncao::class, 'subfuncao', 'codigo');
    }

    /**
     * Get the subFuncao that owns the SagresSubFuncao
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function undOrcamentaria(): BelongsTo
    {
        return $this->belongsTo(SagresUndOrcamentaria::class, 'cod_unid_orc', 'codigo');
    }

    /**
     * Get the subFuncao that owns the SagresSubFuncao
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function getPrograma(): BelongsTo
    {
        return $this->belongsTo(SagresPrograma::class, 'programa', 'codigo');
    }

    /**
     * Get the subFuncao that owns the Acao
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function getAcao(): BelongsTo
    {
        return $this->belongsTo(SagresAcao::class, 'acao', 'codigo');
    }

    /**
     * Get the subFuncao that owns the RecursoVinculado
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function rubricaDespesa(): BelongsTo
    {
        return $this->belongsTo(SagresElementoDespesa::class, 'cod_elem_desp', 'codigo');
    }

    /**
     * Get all of the pagamentos for the SagresPagamento
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function pagamentos(): HasMany
    {
        return $this->hasMany(SagresPagamento::class, 'num_empenho', 'num_empenho')->where('ano', $this->ano);
    }

    /**
     * Get all of the liquidacoes for the SagresLiquidacao
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function liquidacoes(): HasMany
    {
        return $this->hasMany(SagresLiquidacao::class, 'num_empenho', 'num_empenho')->where('ano', $this->ano);
    }

    public function totalLiquidado()
    {
        $total = SagresLiquidacao::where('num_empenho', $this->num_empenho)
        ->where('ano', $this->ano)
        ->sum('valor');
        return number_format($total,2,',','.');
    }

    public function totalPago()
    {
        $total = SagresPagamento::where('num_empenho', $this->num_empenho)->where('ano', $this->ano)->sum('valor');
        return number_format($total,2,',','.');
    }

    public function getDataEmissaoEmpenhoAttribute($value)
    {
        return date('d/m/Y', strtotime($value));
    }

    public function getValorEmpenhadoAttribute($value)
    {
        return number_format($value,2,',','.');
    }
}

resources/views/adm/sagres-empenhos/create.blade.php
@extends('layout.default')

@section('page_toolbar')
<a href={{ route('sagres-empenhos.index') }} class='btn btn-info font-weight-bolder font-size-sm mr-2'>LISTAGEM</a>
@endsection

@section('content')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_description }} {{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            
        </div>
    </div>
    {{--end::Header--}}
    {!! Form::open(['route'=>'sagres-empenhos.store', 'files'=>true]) !!}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Form--}}
        @include('adm.sagres-empenhos.includes._form')
        {{--end::Form--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        <button type='submit' class='btn btn-primary'>Cadastrar</button>
    </div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/adm/sagres-empenhos/edit.blade.php
@extends('layout.default')

@section('page_toolbar')
<a href={{ route('sagres-empenhos.index') }} class='btn btn-info font-weight-bolder font-size-sm mr-2'>LISTAGEM</a>
@endsection

@section('content')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>
            {{ $page_description }} de {{ $page_title }}: #{{$sagresEmpenho->id}}
            </span>
        </h3>
        <div class='card-toolbar'>
            
        </div>
    </div>
    {{--end::Header--}}
    {!! Form::model($sagresEmpenho, ['route'=>['sagres-empenhos.update', $sagresEmpenho->id], 'method'=>'PUT']) !!}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Form--}}
        @include('adm.sagres-empenhos.includes._form')
        {{--end::Form--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        <button type='submit' class='btn btn-success'>Salvar Alterações</button>
    </div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/adm/sagres-empenhos/index.blade.php
@extends('layout.default')

@section('page_toolbar')
<a href='{{ route('sagres-empenhos.create') }}' class='btn btn-info font-weight-bolder font-size-sm mr-2'>CADASTRAR</a>
<a href='javascript:;' data-toggle='modal' data-target='#filter-sagres-empenhos' class='btn btn-primary font-weight-bolder font-size-sm'>FILTRAR</a>
@endsection

@section('content')
@include('adm.sagres-empenhos.includes._filter')

@if (session('message_success'))
    <div class='alert alert-success font-bold'>{{ session('message_success') }}</div>
@endif
@if (session('message_error'))
    <div class='alert alert-danger font-bold'>{{ session('message_error') }}</div>
@endif
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_description }} de {{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Table--}}
        @include('adm.sagres-empenhos.includes._table')
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        {{ $sagresEmpenhos->appends(request()->except(['page']))->links('vendor.pagination.metronic') }}
    </div>
</div>
@endsection

resources/views/adm/sagres-empenhos/show.blade.php
@extends('layout.default')

@section('page_toolbar')
<a href={{ route('sagres-empenhos.index') }} class='btn btn-info font-weight-bolder font-size-sm mr-2'>LISTAGEM</a>
@endsection

@section('content')
@include('adm.sagres-empenhos.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>
            {{ $page_description }} de {{ $page_title }}: #{{$sagresEmpenho->num_empenho}}
            </span>
        </h3>
        <div class='card-toolbar'>

        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Form--}}
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Data</label><br>
                    {{ $sagresEmpenho->data_emissao_empenho }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Número</label><br>
                    {{ $sagresEmpenho->num_empenho }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Credor</label><br>
                    {{ $sagresEmpenho->credor ? $sagresEmpenho->credor->nome : $sagresEmpenho->cpf_cnpj_credor }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Unidade Orçamentária</label><br>
                    {{ @$sagresEmpenho->undOrcamentaria->denominacao }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Função</label><br>
                    {{ @$sagresEmpenho->funcao->nome }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Sub-Função</label><br>
                    {{ @$sagresEmpenho->subfuncao->nome }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Programa</label><br>
                    {{ @$sagresEmpenho->getPrograma->nome }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Ação</label><br>
                    {{ @$sagresEmpenho->getAcao->nome }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Elemento de Despesa</label><br>
                    {{ @$sagresEmpenho->rubricaDespesa->descricao }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Número do Processo</label><br>
                    {{ $sagresEmpenho->num_procedimento }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Valor</label><br>
                    R$ {{ $sagresEmpenho->valor_empenhado }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Valor Liquidado</label><br>
                    R$ {{ $sagresEmpenho->totalLiquidado() }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="font-weight-bolder">Valor Pago</label><br>
                    R$ {{ $sagresEmpenho->totalPago() }}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="font-weight-bolder">Histórico</label><br>
                    {{ $sagresEmpenho->historico }}
                </div>
            </div>
        </div>
        {{--end::Form--}}
    </div>
    {{--end::Body--}}
</div>

<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>
                Pagamentos do {{ $page_title }}: #{{$sagresEmpenho->num_empenho}}
            </span>
        </h3>
        <div class='card-toolbar'>

        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-inverse">
                    <tr>
                        <th>Código do Banco</th>
                        <th>Agência</th>
                        <th>Número da Conta</th>
                        <th>Data</th>
                        <th>Valor</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($sagresEmpenho->pagamentos as $pagamento)
                        <tr>
                            <td scope="row">{{ $pagamento->cod_banco }}</td>
                            <td>{{ $pagamento->num_agencia_bancaria }}</td>
                            <td>{{ $pagamento->num_conta_bancaria }}</td>
                            <td>{{ $pagamento->data }}</td>
                            <td>R$ {{ $pagamento->valor }}</td>
                        </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
    </div>
    {{--end::Body--}}
</div>

<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>
                Liquidações do {{ $page_title }}: #{{$sagresEmpenho->NumEmpenho}}
            </span>
        </h3>
        <div class='card-toolbar'>

        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-inverse">
                    <tr>
                        <th>Número</th>
                        <th>Data</th>
                        <th>Valor</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($sagresEmpenho->liquidacoes as $liquidacao)
                        <tr>
                            <td scope="row">{{ $liquidacao->num_liquidacao }}</td>
                            <td>{{ $liquidacao->data }}</td>
                            <td>R$ {{ $liquidacao->valor }}</td>
                        </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
    </div>
    {{--end::Body--}}
</div>
@endsection