routes/web.php
<?php


use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('home');
Route::get('/orcamentos', 'PagesController@orcamentos')->name('orcamento');
Route::get('/despesas', 'PagesController@despesas')->name('despesas');
Route::get('/receitas', 'PagesController@receitas')->name('receitas');
Route::get('/servidores', 'PagesController@servidores')->name('servidores');
Route::get('/licitacoes', 'PagesController@licitacoes')->name('licitacoes');

Route::get('/contratos', 'PagesController@contratos')->name('contratos');
Route::get('/atas-resgitro-pagemento', 'PagesController@atas')->name('atas');
Route::get('/dispensa-licitacao', 'PagesController@dispensa')->name('dispensa');
Route::get('/concorrencia', 'PagesController@concorrencia')->name('concorrencia');
Route::get('/carta-convite', 'PagesController@cartaConvite')->name('carta');
Route::get('/contrato-pessoa-fisica', 'PagesController@contratoPessoaFisica')->name('contrato.fisica');
Route::get('/contrato-pessoa-juridica', 'PagesController@contratoPessoaJuridica')->name('contrato.juridica');
Route::get('/inexigibilidade', 'PagesController@inexigibilidade')->name('inexigibilidade');
Route::get('/pregao-presencial', 'PagesController@pregaoPresencial')->name('pregao.presencial');
Route::get('/pregao-eletronico', 'PagesController@pregaoEletronico')->name('pregao.eletronico');
Route::get('/tomada-precos', 'PagesController@tomadaDePrecos')->name('tomada.precos');


Route::get('/diarias', 'PagesController@diarias')->name('diarias');
Route::get('/publicacoes-oficiais', 'PagesController@publicacoesOficiais')->name('publicacoes-oficiais');
Route::get('/legislacoes', 'PagesController@legislacoes')->name('legislacoes');
Route::get('/pedidos-esic', 'PagesController@esic');
Route::post('/salvar-pedido', 'PagesController@salvarPedido')->name('salvarPedido');
Route::get('/salvar-pedido/consultar', 'PagesController@consultarPedido')->name('consultarPedido');
Route::post('/responder-pedido', 'PagesController@responderPedido')->name('responderPedido');
Route::get('/covid19', 'PagesController@covid19')->name('covid19');
Route::get('/covid19-despesas', 'PagesController@covid19Desespesas')->name('covid19-despesas');
Route::get('/covid19-receitas', 'PagesController@covid19Receitas')->name('covid19-receitas');
Route::get('/covid19-licitacoes', 'PagesController@covid19Licitacoes')->name('covid19-licitacoes');
Route::get('/covid19-contratos', 'PagesController@covid19Contratos')->name('covid19-contratos');
Route::get('/estatisticas', 'PagesController@estatisticas')->name('estatisticas');
Route::get('/estrutura-organizacional', 'PagesController@estruturas')->name('estrutura-organizacional');
Route::get('/lrf', 'PagesController@lrf')->name('lrf');
Route::get('/verbas', 'PagesController@verbas')->name('verba');
Route::post('/search-options','SearchController@searchOptions')->name('search');
Route::fallback(function () {
    return redirect()->route('home');
});

// Demo routes
// Route::get('/dashboards', 'PagesController@dashboards');
// Route::get('/datatables', 'PagesController@datatables');
// Route::get('/ktdatatables', 'PagesController@ktDatatables');
// Route::get('/select2', 'PagesController@select2');
// Route::get('/jquerymask', 'PagesController@jQueryMask');
// Route::get('/icons/custom-icons', 'PagesController@customIcons');
// Route::get('/icons/flaticon', 'PagesController@flaticon');
// Route::get('/icons/fontawesome', 'PagesController@fontawesome');
// Route::get('/icons/lineawesome', 'PagesController@lineawesome');
// Route::get('/icons/socicons', 'PagesController@socicons');
// Route::get('/icons/svg', 'PagesController@svg');

// Quick search dummy route to display html elements in search dropdown (header search)
// Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

Route::prefix('adm')->group(function () {
    Auth::routes(['register' => false]);
    Route::middleware(['auth'])->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home_adm');
        Route::resource('users', UserController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('app-settings', AppSettingController::class);
        Route::resource('attachments', AttachmentController::class);
        Route::resource('type-documents', TypeDocumentController::class);
        Route::resource('documents', DocumentController::class);
        Route::resource('attachment-documents', AttachmentDocumentController::class);
        Route::resource('verbas', VerbaController::class);
        Route::resource('attachment-verbas', AttachmentVerbaController::class);
        Route::resource('empenhos', EmpenhoController::class);
        Route::resource('attachment-empenhos', AttachmentEmpenhoController::class);
        Route::resource('pagamentos', PagamentoController::class);
        Route::resource('liquidacoes', LiquidacaoController::class);
        Route::resource('receitas', ReceitaController::class);
        Route::resource('attachment-receitas', AttachmentReceitaController::class);
        Route::resource('cargos', CargoController::class);
        Route::resource('servidores', ServidorController::class);
        Route::get('servidores/{id}/restore', [App\Http\Controllers\ServidorController::class, 'restore'])->name('servidores.restore');
        Route::resource('attachment-servidores', AttachmentServidorController::class);
        Route::resource('contratos', ContratoController::class);
        Route::resource('attachment-contratos', AttachmentContratoController::class);
        Route::resource('diarias', DiariaController::class);
        Route::resource('attachment-diarias', AttachmentDiariaController::class);
        Route::resource('tipo-planejamento-orcamentarios', TipoPlanejamentoOrcamentarioController::class);
        Route::resource('arquivo-plan-orcamentarios', ArquivoPlanOrcamentarioController::class);
        Route::resource('covid-resumos', CovidResumoController::class);
        Route::resource('estruturas', EstruturaController::class);
        Route::resource('responsabilidades', ResponsabilidadeController::class);
        Route::resource('arquivo-responsabilidades', ArquivoResponsabilidadeController::class);

        Route::prefix('sicap')->group(function () {
            Route::resource('sicap-empenho', SicapEmpenhoController::class);
            Route::get('sicap-empenho/{id}/restore', [App\Http\Controllers\SicapEmpenhoController::class, 'restore'])->name('sicap-empenho.restore');

            Route::resource('sicap-servidores', SicapServidorController::class);
            Route::get('sicap-servidores/{id}/restore', [App\Http\Controllers\SicapServidorController::class, 'restore'])->name('sicap-servidor.restore');

            Route::resource('sicap-receitas', SicapReceitaController::class);
            Route::get('sicap-receitas/{id}/restore', [App\Http\Controllers\SicapReceitaController::class, 'restore'])->name('sicap-receitas.restore');
        });
        Route::prefix('siap')->group(function () {
            Route::resource('siap-empenho', SiapEmpenhoController::class);
            Route::get('siap-empenho/{id}/restore', [App\Http\Controllers\SiapEmpenhoController::class, 'restore'])->name('siap-empenho.restore');
        });
        Route::prefix('sagres')->group(function () {
            Route::resource('sagres-empenhos', SagresEmpenhoController::class);
            Route::get('sagres-empenho/{id}/restore', [App\Http\Controllers\SagresEmpenhoController::class, 'restore'])->name('sagres-empenho.restore');
        });

        Route::resource('pedidos', PedidoController::class);
        Route::resource('controle-menu',OptionController::class);
        Route::get('controle-submenu/{id}',[App\Http\Controllers\OptionController::class,'editSubmenu'])->name('submenu.edit');
        Route::put('controle-submenu/{id}',[App\Http\Controllers\OptionController::class,'updateSubmenu'])->name('submenu.update');
        Route::resource('respostas', RespostaController::class);
        Route::resource('tipo-pedidos', TipoPedidoController::class);
    });
});

app/Models/Pedido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Pedido extends Model
{
    /** 
     * The attributes that are mass assignable
     * 
     * @var array 
     */
     protected $table = 'pedidos';
     protected $fillable = [
        'name',
        'email',
        'priority',
        'cpf',
        'phone',
        'location',
        'type_answer',
        'typerequest_id',
        'subject',
        'message',
        'anexo',
        'status',
        'serial'
     ];

    /**
     * Get all of the respostas for the Pedido
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function respostas(): HasMany
    {
        return $this->hasMany(Resposta::class);
    }

    /**
     * Get the tipoPedido that owns the Pedido
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tipoPedido(): BelongsTo
    {
        return $this->belongsTo(TipoPedido::class, 'typerequest_id', 'id');
    }

    public function getPriorityExtensoAttribute($value)
    {
        return \Config::get('constants.esic.priority')[$this->priority];
    }

    public function getStatusExtensoAttribute($value)
    {
        return \Config::get('constants.esic.status')[$this->status];
    }

    public function getCreatedAtAttribute($value)
    {
        return date('d/m/Y H:i:s', strtotime($value));
    }

}

resources/views/pages/contratos.blade.php
@extends('layout.public')

@section('content')
{{-- @include('adm.contratos.includes._filter') --}}
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            <div class="btn-group btn-group-lg mr-5" role="group" aria-label="Large button group">
                <a href="{{ route(Route::currentRouteName(), ['export'=>'xml', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">XML</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'csv', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">CSV</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'json', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">JSON</a>
            </div>
            <a href='javascript:;' data-toggle='modal' data-target='#filter-contratos' class='btn btn-primary font-weight-bolder font-size-sm'>FILTRAR</a>
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
        @endif
        {{--begin::Table--}}

        @include('adm.contratos.includes._table')
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right border d-flex flex-row  align-items-center justify-content-end'>
        {{ $contratos->appends(request()->except(['page']))->links('vendor.pagination.metronic')}}
    </div>
</div>

<div class='modal fade' id='filter-contratos' tabindex='-1' role='dialog' aria-labelledby='filter-contratos-title' aria-hidden='true'>
    <div class='modal-dialog modal-lg' role='document'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h5 class='modal-title'>Filtrar contratos</h5>
                <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                </button>
            </div>
            {!! Form::open(['method'=>'GET']) !!}
            <div class='modal-body'>
                <div class='container-fluid'>
                    <div class='row'>
                        <div class='col-md-4'>
                            <div class='form-group'>
                                {!! Form::label('orgao', 'Órgão') !!}
                                {!! Form::text('orgao', request('orgao'), [
                                    'class'=>(!empty($errors->default->first('orgao'))) ? 'form-control form-control-solid is-invalid':'form-control form-control-solid'
                                ]) !!}
                            </div>
                        </div>
                        <div class='col-md-8'>
                            <div class='form-group'>
                                {!! Form::label('modalidade', 'Modalidade') !!}
                                {!! Form::text('modalidade', request('modalidade'), [
                                    'class'=>(!empty($errors->default->first('modalidade'))) ? 'form-control form-control-solid is-invalid':'form-control form-control-solid'
                                ]) !!}
                            </div>
                        </div>
                        <div class='col-md-4'>
                            <div class='form-group'>
                                {!! Form::label('data_hora', 'Data/Hora') !!}
                                <input type="datetime-local" name="data_hora" value="{{ request('data_hora') }}" class="{{ (!empty($errors->default->first('data_hora'))) ? 'form-control form-control-solid is-invalid':'form-control form-control-solid' }}">
                            </div>
                        </div>
                        <div class='col-md-4'>
                            <div class='form-group'>
                                {!! Form::label('valor', 'Preço') !!}
                                {!! Form::text('valor', request('valor'), [
                                    'class'=>(!empty($errors->default->first('valor'))) ? 'form-control decimal form-control-solid is-invalid':'form-control decimal form-control-solid'
                                ]) !!}
                            </div>
                        </div>
                        <div class='col-md-4'>
                            <div class='form-group'>
                                {!! Form::label('status', 'Status') !!}
                                {!! Form::select('status', Config::get('constants.licitacoes.status'), request('status'), [
                                    'class'=>(!empty($errors->default->first('status'))) ? 'form-control select2 form-control-solid is-invalid':'form-control select2 form-control-solid',
                                    'placeholder' => 'Selecione...',
                                    'style' => 'width:100%'
                                ]) !!}
                            </div>
                        </div>
                        <div class='col-md-6'>
                            <div class='form-group'>
                                {!! Form::label('vencedor', 'Vencedor') !!}
                                {!! Form::text('vencedor', request('vencedor'), [
                                    'class'=>(!empty($errors->default->first('vencedor'))) ? 'form-control form-control-solid is-invalid':'form-control form-control-solid'
                                ]) !!}
                            </div>
                        </div><div class='col-md-6'>
                            <div class='form-group'>
                                {!! Form::label('objeto', 'Objeto') !!}
                                {!! Form::text('objeto', request('objeto'), [
                                    'class'=>(!empty($errors->default->first('objeto'))) ? 'form-control form-control-solid is-invalid':'form-control form-control-solid'
                                ]) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-dismiss='modal'>Fechar</button>
                <a href='{{ route('contratos.index') }}' class='btn btn-info'>Limpar</a>
                <button type='submit' class='btn btn-primary'>Filtrar</button>

            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/pages/despesas-covid19.blade.php
@extends('layout.public')

@section('content')
@include('adm.empenhos.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            <a href='javascript:;' data-toggle='modal' data-target='#filter-empenhos' class='btn btn-primary font-weight-bolder font-size-sm'>FILTRAR</a>
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
        @endif
        {{--begin::Table--}}
        {{-- {!! Form::hidden('route', route('despesas'), ['id'=>'route']) !!} --}}

        @include('adm.empenhos.includes._table')
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        {{ $empenhos->appends(request()->except(['page']))->links('vendor.pagination.metronic') }}
    </div>
</div>
@endsection

resources/views/pages/despesas.blade.php
@extends('layout.public')

@section('content')
@include('adm.empenhos.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            <div class="btn-group btn-group-lg mr-5" role="group" aria-label="Large button group">
                <a href="{{ route(Route::currentRouteName(), ['export'=>'xml', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">XML</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'csv', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">CSV</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'json', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">JSON</a>
            </div>
            <a href='javascript:;' data-toggle='modal' data-target='#filter-empenhos' class='btn btn-primary font-weight-bolder font-size-sm'>FILTRAR</a>
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Table--}}
        @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
        @endif
        {{-- {!! Form::hidden('route', route('despesas'), ['id'=>'route']) !!} --}}
        @switch($appSetting->prioridade)
            @case('manual')
                @include('adm.empenhos.includes._table')
                @break
            @case('sicap')
                @php($sicapEmpenho = $empenhos)
                @include('adm.sicap-empenho.includes._table')
                @break
            @case('siap')
                @php($siapEmpenho = $empenhos)
                @include('adm.siap-empenho.includes._table')
                @break
            @case('sagres')
                @php($sagresEmpenhos = $empenhos)
                @include('adm.sagres-empenhos.includes._table')
                @break
            @default
                @include('adm.empenhos.includes._table')
        @endswitch
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        {{ $empenhos->appends(request()->except(['page']))->links('vendor.pagination.metronic') }}
    </div>
</div>
@endsection

resources/views/pages/estruturas.blade.php
@extends('layout.public')

@section('content')
@include('adm.empenhos.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }} - Órgãos e Horários de Funcionamento</span>
        </h3>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Table--}}
        @if (count($estruturas) > 0)
        <div class="row">
            @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
            @endif
            <div class="col-3">
                <ul class="nav flex-column nav-pills">
                    @foreach ($estruturas as $key => $estrutura)
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {{ ($key == 0) ? 'active':'' }}" id="tab{{$key}}" data-toggle="tab" href="#content{{$key}}" role="tab" aria-controls="content{{$key}}" aria-selected="true">
                            {{ $estrutura->order }}. {{ $estrutura->title }}
                        </a>
                    </li>
                    @endforeach
                </ul>
            </div>
            <div class="col-9">
                <div class="tab-content" id="myTabContent">
                    @foreach ($estruturas as $key => $estrutura)
                    <div class="tab-pane fade show {{ ($key == 0) ? 'active':'' }}" id="content{{$key}}" role="tabpanel" aria-labelledby="content{{$key}}-tab">
                        <div class="col-md-12 mb-10">
                            {!! $estrutura->description !!}
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
            {{-- <ul class="nav flex-column nav-tabs" id="myTab" role="tablist">
                @foreach ($estruturas as $key => $estrutura)
                <li class="nav-item" role="presentation">
                <a class="nav-link {{ ($key == 0) ? 'active':'' }}" id="tab{{$key}}" data-toggle="tab" href="#content{{$key}}" role="tab" aria-controls="content{{$key}}" aria-selected="true">{{ $estrutura->title }}</a>
                </li>
                @endforeach
            </ul>
            <div class="tab-content" id="myTabContent">
                @foreach ($estruturas as $key => $estrutura)
                <div class="tab-pane fade show {{ ($key == 0) ? 'active':'' }}" id="content{{$key}}" role="tabpanel" aria-labelledby="content{{$key}}-tab">
                    <div class="col-md-12">
                        {!! $estrutura->description !!}
                    </div>
                </div>
                @endforeach
            </div> --}}
        @endif
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
</div>
@endsection

resources/views/pages/orcamentos.blade.php
@extends('layout.public')

@section('content')
@include('adm.empenhos.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            <div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
                <a href="{{ route(Route::currentRouteName(), ['export'=>'xml', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">XML</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'csv', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">CSV</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'json', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">JSON</a>
            </div>
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        {{--begin::Table--}}
        @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
        @endif
        @if (count($tipos) > 0)
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                @foreach ($tipos as $key => $tipo)
                <li class="nav-item" role="presentation">
                <a class="nav-link {{ ($key == 0) ? 'active':'' }}" id="tab{{$key}}" data-toggle="tab" href="#content{{$key}}" role="tab" aria-controls="content{{$key}}" aria-selected="true">{{ $tipo->name }}</a>
                </li>
                @endforeach
            </ul>
            <div class="tab-content" id="myTabContent">
                @foreach ($tipos as $key => $tipo)
                <div class="tab-pane fade show {{ ($key == 0) ? 'active':'' }}" id="content{{$key}}" role="tabpanel" aria-labelledby="content{{$key}}-tab">
                    <div class="col-md-12">
                        <p class="my-10">{{ $tipo->description }}</p>
                        @foreach ($tipo->arquivos as $arquivo)
                        <p class="my-10">
                            <a href="{{ asset($arquivo->attachment->path) }}" class="btn btn-primary btn-sm" target="_blank">{{ $arquivo->name }}</a> - {{ $arquivo->description }}
                        </p>
                        @endforeach
                    </div>
                </div>
                @endforeach
            </div>
        @endif
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
</div>
@endsection

resources/views/pages/servidores.blade.php
@extends('layout.public')

@section('content')
@include('adm.servidores.includes._filter')
<div class='card card-custom gutter-b'>
    {{--begin::Header--}}
    <div class='card-header border-0 py-5'>
        <h3 class='card-title align-items-start flex-column'>
            <span class='card-label font-weight-bolder text-dark'>{{ $page_title }}</span>
        </h3>
        <div class='card-toolbar'>
            <div class="btn-group btn-group-lg mr-5" role="group" aria-label="Large button group">
                <a href="{{ route(Route::currentRouteName(), ['export'=>'xml', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">XML</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'csv', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">CSV</a>
                <a href="{{ route(Route::currentRouteName(), ['export'=>'json', 'datetime'=>date('YmdHis')]) }}" target="_blank" class="btn btn-outline-secondary">JSON</a>
            </div>
            <a href='javascript:;' data-toggle='modal' data-target='#filter-servidores' class='btn btn-primary font-weight-bolder font-size-sm'>FILTRAR</a>
        </div>
    </div>
    {{--end::Header--}}
    {{--begin::Body--}}
    <div class='card-body py-0'>
        @if ($appSetting->view_last_update)
            <div class="col-12">
                <p class="text-center">
                    <small>Ultima Atualização: <strong>{{ $last_update ? date('d/m/Y H:i:s', strtotime($last_update->created_at)) : '' }}</strong></small>
                </p>
            </div>
        @endif
        {{--begin::Table--}}
        {{-- {!! Form::hidden('route', route('despesas'), ['id'=>'route']) !!} --}}
        @switch($appSetting->prioridade_servidores)
            @case('manual')
                @include('adm.servidores.includes._table')
                @break
            @case('sicap')
                @php($sicapServidores = $servidores)
                @include('adm.sicap-servidores.includes._table')
                @break
            @default
                @include('adm.servidores.includes._table')
        @endswitch
        {{--end::Table--}}
    </div>
    {{--end::Body--}}
    <div class='card-footer text-right'>
        {{ $servidores->appends(request()->except(['page']))->links('vendor.pagination.metronic') }}
    </div>
</div>
@endsection